version: '3.7'
# The above version is the Docker Compose manifest's version, not the Canasta Docker Compose stack's version.
#
# --- Canasta Stack for Docker Compose ---
#
# If you need to make changes to the stack, make them here.
# Only edits to docker-compose.override.yml are officially supported by Canasta.
#
# Uncomment the commented services and add lines below them if you would like to make additional customizations to them.
services:
  #db:
  web:
    image: ghcr.io/canastawiki/canasta:1.3.0
    volumes:
      - ./resources:/var/www/mediawiki/resources
  elasticsearch:
    deploy:
      replicas: 0
  caddy:
    environment:
      CADDY_HOST: ${CADDY_HOST:-${MW_SITE_FQDN}:${HTTPS_PORT}}
      CADDY_TARGET: ${CADDY_TARGET:-varnish:80}
  #varnish:
